# -*- coding: utf-8 -*-

{
    "name": "Payroll Reports",
    'summary': """Payroll Reports""",
    "category": "Human Resources/Payroll Reports",
    "version": "14.0.0.0.1",
    "author": "PING TECHNOLOGIES LIMITED",
    "license": "OPL-1",
    "website": "pingtt.com",
    "description": """Payroll Reports""",
    "depends": ['hr_payroll', 'hr', 'l10n_tt_hr_payroll'],
    "data": [
            'security/ir.model.access.csv',
            'wizard/td4_report_wizard_view.xml',
            'views/year_periods_view.xml',
            'report/report_employee.xml',
            'views/employee_report.xml',
            'views/assets.xml',
            'views/hr_employee_view.xml',
            'views/res_company_view.xml',
            'wizard/td4_edit_view.xml',
            'report/summary_report.xml',
            'wizard/addition_deduction_wizard.xml',
            'report/monthly_payroll_additions_report.xml',
            'report/monthly_payroll_deductions_report.xml',
            'wizard/tax_report_wizard.xml',
            'report/monthly_tax_report.xml',
            'data/account_data.xml',
            'wizard/nis_report_wizard.xml',
            'report/nis_report.xml',
            'wizard/monthly_payroll_summary_report_wizard.xml',
            'report/monthly_payroll_summary_report.xml',
            'wizard/nis_report_due_wizard.xml',
            'report/nis_report_dues.xml',
             ],
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    'sequence': 1
}